include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = testgradient

testgradient_OBJC_FILES = gradient_test.m

testgradient_TOOL_LIBS = -lgnustep-gui -lgnustep-base

include $(GNUSTEP_MAKEFILES)/tool.make
