
all: ToastNotifications-0.dll

clean:
	rm -rf obj

obj:
	mkdir -p obj

install: ToastNotifications-0.dll

ifeq ($(debug),yes)
ToastNotifications-0.dll: obj ToastNotifications/Debug/ToastNotifications.dll
	cp -p ToastNotifications/Debug/ToastNotifications.dll obj/ToastNotifications-0.dll
else
ToastNotifications-0.dll: obj ToastNotifications/Release/ToastNotifications.dll
	cp -p ToastNotifications/Release/ToastNotifications.dll obj/ToastNotifications-0.dll
endif