ADDITIONAL_INCLUDE_DIRS += -I$(GNUSTEP_BUILD_DIR)/../../Headers \
                           -I$(GNUSTEP_BUILD_DIR)/../../Source \
                           -I../../Headers -I../../Source \
                           -I$(GNUSTEP_BUILD_DIR)/../.. -I../..
